import { config } from 'dotenv';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const projectRoot = process.cwd();
const envFilePath = resolve(projectRoot, '.env');

const result = config({ path: envFilePath });
const parsedEnv = result.parsed ?? {};

const getValue = (key, fallback = '') => {
  const fromProcess = process.env[key];
  if (fromProcess && fromProcess.length > 0) {
    return fromProcess;
  }

  const fromFile = parsedEnv[key];
  if (fromFile && fromFile.length > 0) {
    return fromFile;
  }

  return fallback;
};

const envObject = {
  NG_APP_API_URL: getValue('NG_APP_API_URL', 'http://192.168.1.69:3000/api'),
  NG_APP_QUEUE_URL: getValue('NG_APP_QUEUE_URL', 'http://192.168.1.69:3000'),
  NG_APP_MP_PUBLIC_KEY: getValue('NG_APP_MP_PUBLIC_KEY', ''),
};

const targetPath = resolve(projectRoot, 'src', 'app', 'config', 'generated-env.ts');
mkdirSync(dirname(targetPath), { recursive: true });

const fileContent = `// Auto-generated by scripts/generate-env.mjs\n` +
  `// Do not edit this file manually.\n` +
  `export const generatedEnv = ${JSON.stringify(envObject, null, 2)} as const;\n`;

writeFileSync(targetPath, fileContent, { encoding: 'utf8' });

console.log('[env] Configurações geradas em', targetPath);
